dist: bionic
language: c
os:
  - linux
compiler:
  - gcc
install:
  - sudo apt-get install cmake
  - sudo apt-get install libgtest-dev
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib
  - cd -
script:
  - cmake CMakeLists.txt
  - make
matrix:
  include:
  - env:
      - TEST="CppCheck"
    script:
      - cmake -DENABLE_CPPCHECK=ON -DCMAKE_CXX_COMPILER="g++-6" CMakeLists.txt
      - make
      - make check
after_success:
  - bash <(curl -s https://codecov.io/bash)
