dist: bionic
language: c
os:
  - linux
compiler:
  - gcc
install:
  - sudo apt-get install cmake
  - sudo apt-get install libgtest-dev
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib
  - cd -
script:
  - cmake CMakeLists.txt
  - make
matrix:
  include:
  - env:
      - TEST="CppCheck"
    script:
      - cmake -DENABLE_CPPCHECK=ON CMakeLists.txt
      - make
      - sudo apt-get install cppcheck
      - cppcheck .
  
  #
  # Clang Tidy
  #
  - os: linux
    env:
      - TEST="Clang Tidy"
    addons:
      apt:
        sources:
          - llvm-toolchain-trusty-4.0
        packages:
          - clang-4.0
          - clang-tidy-4.0
    script:
      - cmake -DENABLE_CLANG_TIDY=ON  CMakeLists.txt
      - make
      - make tidy
after_success:
  - bash <(curl -s https://codecov.io/bash)
