dist: bionic
language: c
os:
  - linux
compiler:
  - gcc
install:
  - sudo apt-get install cmake
  - sudo apt-get install libgtest-dev
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib
  - cd -
script:
  - cmake CMakeLists.txt
  - make
matrix:
  include:
  - env:
      - TEST="CppCheck"
    script:
      - cmake -DENABLE_CPPCHECK=ON CMakeLists.txt
      - make
      - sudo apt-get install cppcheck
      - cppcheck .
  
  #
  # Clang Tidy
  #
  - os: linux
    env:
      - TEST="Clang Tidy"
    addons:
      apt:
        sources:
          - llvm-toolchain-bionic-7.0
        packages:
          - clang-7.0
          - clang-tidy-7.0
    script:
      - cmake -DENABLE_CLANG_TIDY=ON  CMakeLists.txt
      - make
      - make tidy > output.txt
      - |
        if [[ -n $(grep "warning: " output.txt) ]] || [[ -n $(grep "error: " output.txt) ]]; then
            echo "You must pass the clang tidy checks before submitting a pull request"
            echo ""
            grep --color -E '^|warning: |error: ' output.txt
            exit -1;
        else
            echo -e "\033[1;32m\xE2\x9C\x93 passed:\033[0m $1";
        fi
after_success:
  - bash <(curl -s https://codecov.io/bash)
